### PR TITLE
Add support for Geant4@11.2

### LINKED ISSUE #1074: Build errors with GEANT4 11.2.0
Hi,
  Looks like `celeritas v0.4.1` or latest `devel` branch failed to build with Geant 11.2.0. The build error I get is [a]

```
In file included from <path>/geant4/11.2.0-369aba6a4851f900c7e85d3309525223/include/Geant4/G4TouchableHandle.hh:42,
                 from <path>/geant4/11.2.0-369aba6a4851f900c7e85d3309525223/include/Geant4/G4StepPoint.hh:47,
                 from <path>/geant4/11.2.0-369aba6a4851f900c7e85d3309525223/include/Geant4/G4Step.hh:53,
                 from <path>/geant4/11.2.0-369aba6a4851f900c7e85d3309525223/include/Geant4/G4VParticleChange.hh:65,
                 from <path>/geant4/11.2.0-369aba6a4851f900c7e85d3309525223/include/Geant4/G4VProcess.hh:48,
                 from <path>/geant4/11.2.0-369aba6a4851f900c7e85d3309525223/include/Geant4/G4Transportation.hh:46,
                 from <path>/celeritas/src/celeritas/ext/GeantGeoParams.cc:14:
<path>/geant4/11.2.0-369aba6a4851f900c7e85d3309525223/include/Geant4/G4VTouchable.hh:39:7: error: conflicting declaration 'using G4VTouchable = class G4TouchableHistory'
   39 | using G4VTouchable = G4TouchableHistory;
      |       ^~~~~~~~~~~~
In file included from <path>/celeritas/src/celeritas/ext/GeantGeoData.hh:18,
                 from <path>/celeritas/src/celeritas/ext/GeantGeoParams.hh:19,
                 from <path>/celeritas/src/celeritas/ext/GeantGeoParams.cc:8:
<path>/celeritas/src/celeritas/ext/detail/GeantGeoNavCollection.hh:20:7: note: previous declaration as 'class G4VTouchable'
   20 | class G4VTouchable;
      |       ^~~~~~~~~~~~
In file included from <path>/geant4/11.2.0-369aba6a4851f900c7e85d3309525223/include/Geant4/G4StepPoint.hh:191:
<path>/geant4/11.2.0-369aba6a4851f900c7e85d3309525223/include/Geant4/G4StepPoint.icc: In member function 'G4VPhysicalVolume* G4StepPoint::GetPhysicalVolume() const':
<path>/geant4/11.2.0-369aba6a4851f900c7e85d3309525223/include/Geant4/G4StepPoint.icc:158:21: error: invalid use of incomplete type 'class G4VTouchable'
  158 |   return fpTouchable->GetVolume();
      |                     ^~
<path>/celeritas/src/celeritas/ext/detail/GeantGeoNavCollection.hh:20:7: note: forward declaration of 'class G4VTouchable'
   20 | class G4VTouchable;
```

### PR DESCRIPTION
**Pull request by whokion**
# Updates for Geant4 11.2 
 - Change G4VTouchable to G4TouchableHistory 
 - Use G4EmParameters::Instance()->SetLPM instead of G4EmModel::SetLPMFlag

# Description
This MR updates compatibility of celeritas to the new version of Geant4 11.2

Fixes #1074

### CODE REVIEW

**Review by sethrj — CHANGES_REQUESTED** [review]
Thanks @whokion ! But these changes need to be guarded with G4VERSION macros (there are examples elsewhere) so that it still works all the way back to Geant4 10.5...

**Comment by whokion** [comment]
As far as I can see, these updates should be good for 10.5 and later without the version guard.

File: src/celeritas/ext/detail/GeantBremsstrahlungProcess.cc [hunk 1]
```diff
@@ -107,7 +107,7 @@ void GeantBremsstrahlungProcess::InitialiseEnergyLossProcess(
         em_model->SetLowEnergyLimit(energy_min);
         em_model->SetHighEnergyLimit(energy_limit);
         em_model->SetSecondaryThreshold(em_parameters->BremsstrahlungTh());
-        em_model->SetLPMFlag(false);
+        G4EmParameters::Instance()->SetLPM(false);
```
Comment (amandalund) [inline src/celeritas/ext/detail/GeantBremsstrahlungProcess.cc]: I think this should be removed: if the model selection is "all", won't this make the LPM flag in the EM parameters false when the relativistic model is added?

File: src/celeritas/ext/detail/GeantBremsstrahlungProcess.cc [hunk 2]
```diff
@@ -128,7 +128,6 @@ void GeantBremsstrahlungProcess::InitialiseEnergyLossProcess(
             em_model->SetLowEnergyLimit(energy_limit);
             em_model->SetHighEnergyLimit(energy_max);
             em_model->SetSecondaryThreshold(em_parameters->BremsstrahlungTh());
-            em_model->SetLPMFlag(em_parameters->LPM());
```
Comment (amandalund) [inline src/celeritas/ext/detail/GeantBremsstrahlungProcess.cc:131]: This line may be required with older Geant4 versions to set the LPM flag correctly, since the relativistic model doesn't get it from the EM parameters in that case.

File: src/celeritas/ext/detail/GeantBremsstrahlungProcess.cc (hunk 1 above)
Comment (whokion) [reply src/celeritas/ext/detail/GeantBremsstrahlungProcess.cc]: Okay, I overlooked that [G4SeltzerBergerModel](https://geant4.kek.jp/lxr/ident?v=11.1.2;i=G4SeltzerBergerModel) is now derived from [G4VEmModel](https://geant4.kek.jp/lxr/ident?i=G4VEmModel).

File: src/celeritas/ext/detail/GeantBremsstrahlungProcess.cc (hunk 2 above)
Comment (whokion) [reply src/celeritas/ext/detail/GeantBremsstrahlungProcess.cc:131]: Okay, you are right. I will put a version guard here.  Thanks.

**Comment by whokion** [comment]
@sethrj Why can I include <G4Version.hh> (or <G4Touchable.hh>) from `GeantGeoUtils.hh`?

**Review by sethrj — APPROVED** [review]
I added a somewhat hacky `CELERITAS_GEANT4_VERSION` version macro via  the `celeritas_sys_config` which doesn't require anything downstream to link against geant4. So this now builds on 11.0 and 11.2.

**Comment by sethrj** [comment]
I'm still having trouble getting this to work at runtime with geant4 11.2. Trying to setup the photoelectric model gives:
```
G4LivermorePhotoElectricModel data file </opt/spack/opt/spack/sonoma/geant4-data/11.2.0/6vfum26/share/geant4-data-11.2.0/G4EMLOW8.5/epics2017/phot/pe-cs-82.dat> is not opened!
```
G4EMLOW8.5 exists but epics2017 doesn't!

Looks like this could be related to geant4 change `emutils-V11-00-23`??

**Comment by amandalund** [comment]
Odd, I do see the data in `G4EMLOW8.5/epics2017/phot/`...

**Comment by sethrj** [comment]
OK, somehow it looks like EMLOW 6.5 got aliased into my 8.5 directory... weird!
