### ISSUE TITLE
Build errors with GEANT4 11.2.0

### ISSUE THREAD

**Issue by smuzaffar** [celeritas-project/celeritas#1074]
Hi,
  Looks like `celeritas v0.4.1` or latest `devel` branch failed to build with Geant 11.2.0. The build error I get is [a]

```
In file included from <path>/geant4/11.2.0-369aba6a4851f900c7e85d3309525223/include/Geant4/G4TouchableHandle.hh:42,
                 from <path>/geant4/11.2.0-369aba6a4851f900c7e85d3309525223/include/Geant4/G4StepPoint.hh:47,
                 from <path>/geant4/11.2.0-369aba6a4851f900c7e85d3309525223/include/Geant4/G4Step.hh:53,
                 from <path>/geant4/11.2.0-369aba6a4851f900c7e85d3309525223/include/Geant4/G4VParticleChange.hh:65,
                 from <path>/geant4/11.2.0-369aba6a4851f900c7e85d3309525223/include/Geant4/G4VProcess.hh:48,
                 from <path>/geant4/11.2.0-369aba6a4851f900c7e85d3309525223/include/Geant4/G4Transportation.hh:46,
                 from <path>/celeritas/src/celeritas/ext/GeantGeoParams.cc:14:
<path>/geant4/11.2.0-369aba6a4851f900c7e85d3309525223/include/Geant4/G4VTouchable.hh:39:7: error: conflicting declaration 'using G4VTouchable = class G4TouchableHistory'
   39 | using G4VTouchable = G4TouchableHistory;
      |       ^~~~~~~~~~~~
In file included from <path>/celeritas/src/celeritas/ext/GeantGeoData.hh:18,
                 from <path>/celeritas/src/celeritas/ext/GeantGeoParams.hh:19,
                 from <path>/celeritas/src/celeritas/ext/GeantGeoParams.cc:8:
<path>/celeritas/src/celeritas/ext/detail/GeantGeoNavCollection.hh:20:7: note: previous declaration as 'class G4VTouchable'
   20 | class G4VTouchable;
      |       ^~~~~~~~~~~~
In file included from <path>/geant4/11.2.0-369aba6a4851f900c7e85d3309525223/include/Geant4/G4StepPoint.hh:191:
<path>/geant4/11.2.0-369aba6a4851f900c7e85d3309525223/include/Geant4/G4StepPoint.icc: In member function 'G4VPhysicalVolume* G4StepPoint::GetPhysicalVolume() const':
<path>/geant4/11.2.0-369aba6a4851f900c7e85d3309525223/include/Geant4/G4StepPoint.icc:158:21: error: invalid use of incomplete type 'class G4VTouchable'
  158 |   return fpTouchable->GetVolume();
      |                     ^~
<path>/celeritas/src/celeritas/ext/detail/GeantGeoNavCollection.hh:20:7: note: forward declaration of 'class G4VTouchable'
   20 | class G4VTouchable;
```

**Comment by sethrj** [comment]
Thanks @smuzaffar . This error looks like a simple IWYU but we'll make sure everything builds as expected first... and we'll try to be more on top of the Geant4 releases in the future now that we have downstream dependents!

**Comment by whokion** [comment]
Following up with MR, https://github.com/celeritas-project/celeritas/pull/1075
