### PR TITLE
Add new capabilities to run CMS with sensitive detectors

### PR DESCRIPTION
**Pull request by sethrj**
- If multiple logical volumes share the same SD name, create a single SD to share among them
- Add the ability to set the number of streams manually
- Add an option to strip GDML pointers from the input file for the demo-geant app
- Fix a crash when creating the hit manager when multiple volumes have the same name
- Be smarter about appending uniquifying pointers when exporting to VecGeom

@whokion @amandalund With the new `/setup/stripGDMLPointers true` option, I can now successfully run CMS run 3 through the standalone app: see https://github.com/celeritas-project/benchmarks/blob/main/full-cms-test/demo-geant-cpu.mac .

There are still a bunch of warning messages such as:
```
VecgeomParams.cc:290: warning: Geometry contains duplicate volume names: "CTPPS_210_Left_Station_RP_210_Left_Station_Hor_Vacuum@0x60000051c160" (1603), "CTPPS_210_Left_Station_RP_210_Left_Station_Hor_Vacuum@0x60000051c160" (1601), "CTPPS_210_Left_Station_RP_210_Left_Station_Hor_Vacuum@0x60000051c160" (1517),
...
GeoMaterialParams.cc:154: warning: Some geometry volumes do not have known material IDs: pixfwdInnerDiskZplus_PixelForwardInnerDiskOuterRing_seg_1@0x11fe571c0, pixfwdInnerDiskZplus_PixelForwardInnerDiskOuterRing_seg_2@0x11fe572f0,
...
```
but these names are only inside of "union" solids, and I think they're just an artifact of how VecGeom builds temporary volumes that seem not to show up in the actual geometry.

### CODE REVIEW

**Comment by sethrj** [comment]
The last round of fixes will conflict with #557 .

**Comment by whokion** [comment]
@sethrj I have a compilation error with the latest update:
```
celeritas/test/orange/OrangeGeoTestBase.hh:117:23: error: invalid use of incomplete type ‘class celeritas::OrangeParams’
  117 |         return params_->num_volumes();
```

**Comment by sethrj** [comment]
Sorry @whokion , that's what I get for only building one test and the app. Everything now builds on my laptop, hope that fixes it!

**Comment by whokion** [comment]
Just for records, there are still two known issues running demo-geant-integration on GPU (even though this MR may not be directly responsible for these failures):
 
1) failure from demo-geant-integration simple-cms-test.mac  (with the default, maxNumTracks=2048) - runs okay, if maxNumTracks=1024
```
celeritas/src/celeritas/em/interactor/LivermorePEInteractor.hh:135:
celeritas: internal assertion failed: inc_energy_ > 0
```
2) failure with cms-run3.gdml
```
      issued by : celeritas/ext/VecgeomParams.cc:213
internal assertion failed: world_top_devptr != nullptr
```

**Comment by amandalund** [comment]
I am also still hitting `internal assertion failed: world_top_devptr != nullptr` with cms-run3 -- @sethrj it sounds like you are not (or are running on the CPU)?

And probably not related to this PR, but the following tests are now failing for me (vecgeom, debug on, reldeb build):
```console
The following tests FAILED:
	 90 - celeritas/global/Stepper:TestEm3NoMsc.* (Failed)
	142 - app/demo-loop (Failed)
	144 - app/demo-geant-integration (Subprocess aborted)
```

**Comment by sethrj** [comment]
@amandalund Yes, this was with CPU just on my laptop.

**Review by amandalund — APPROVED** [review]
Thanks for the fixes and improvements @sethrj!
